[package]
name = "win"
version = "0.1.0"
authors = ["Neal Li <haiwei8086@gmail.com>"]

[dependencies]
libc = "0.2.11"
winapi = "0.2.7"
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
ws2_32-sys = "0.2.1"
nix = "0.5.0"
rustc-serialize = "0.3.21"
